// File: app/data/certifications.js
export const certifications = [
  {
    id: 1,
    title: "AWS Solutions Architect Professional",
    organization: "Amazon Web Services",
    category: "cloud",
    status: "Active",
    issueDate: "February 2024",
    expiryDate: "February 2027",
    credentialId: "AWS-SAP-2024-TM-001234",
    description:
      "Advanced certification demonstrating expertise in designing distributed systems on AWS platform with focus on scalability, security, and cost optimization.",
    skills: [
      "AWS Architecture",
      "CloudFormation",
      "Lambda",
      "RDS",
      "VPC",
      "IAM",
      "S3",
      "CloudWatch",
    ],
    score: "892/1000",
    certificateUrl: "https://aws.amazon.com/verification/TM001234",
    verifyUrl: "https://aws.amazon.com/certification/verify/TM001234",
    logo: "https://d1.awsstatic.com/training-and-certification/certification-badges/AWS-Certified-Solutions-Architect-Professional_badge.69d82ff1b2861e1089539e31550c7c85484b0c8b.png",
  },
  {
    id: 2,
    title: "Google Cloud Professional Developer",
    organization: "Google Cloud Platform",
    category: "cloud",
    status: "Active",
    issueDate: "January 2024",
    expiryDate: "January 2026",
    credentialId: "GCP-PD-2024-TM-567890",
    description:
      "Professional-level certification for designing, building, and deploying applications on Google Cloud Platform.",
    skills: [
      "GCP Services",
      "Kubernetes",
      "App Engine",
      "Cloud Functions",
      "BigQuery",
      "Pub/Sub",
    ],
    score: "85%",
    certificateUrl: "https://cloud.google.com/certification/cloud-developer",
    verifyUrl: "https://google.accredible.com/567890",
    logo: "https://cloud.google.com/_static/cloud/images/social-icon-google-cloud-1200-630.png",
  },
  {
    id: 3,
    title: "Certified Kubernetes Administrator",
    organization: "Cloud Native Computing Foundation",
    category: "cloud",
    status: "Active",
    issueDate: "December 2023",
    expiryDate: "December 2026",
    credentialId: "CKA-2023-TM-112233",
    description:
      "Hands-on certification demonstrating skills in Kubernetes administration, including cluster management, networking, and security.",
    skills: [
      "Kubernetes",
      "Docker",
      "Container Orchestration",
      "Cluster Management",
      "Pod Networking",
    ],
    score: "92%",
    certificateUrl:
      "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/",
    verifyUrl: "https://ti-user-certificates.s3.amazonaws.com/cka-112233.pdf",
  },
  {
    id: 4,
    title: "Meta React Developer Professional",
    organization: "Meta (Facebook)",
    category: "development",
    status: "Active",
    issueDate: "November 2023",
    expiryDate: "November 2025",
    credentialId: "META-RD-2023-TM-445566",
    description:
      "Professional certification covering advanced React concepts, hooks, state management, and modern development practices.",
    skills: [
      "React.js",
      "Redux",
      "Hooks",
      "Context API",
      "Testing",
      "Performance Optimization",
    ],
    score: "94%",
    certificateUrl:
      "https://www.coursera.org/professional-certificates/meta-react-native",
    verifyUrl: "https://coursera.org/verify/professional-cert/445566",
  },
  {
    id: 5,
    title: "MongoDB Certified Developer",
    organization: "MongoDB Inc.",
    category: "data",
    status: "Active",
    issueDate: "October 2023",
    expiryDate: "October 2026",
    credentialId: "MONGO-DEV-2023-TM-778899",
    description:
      "Certification demonstrating proficiency in MongoDB database design, querying, indexing, and application development.",
    skills: [
      "MongoDB",
      "Aggregation Framework",
      "Indexing",
      "Replication",
      "Sharding",
      "Schema Design",
    ],
    score: "88%",
    certificateUrl: "https://university.mongodb.com/certification",
    verifyUrl: "https://university.mongodb.com/verify/778899",
  },
  {
    id: 6,
    title: "Certified Ethical Hacker (CEH)",
    organization: "EC-Council",
    category: "security",
    status: "Active",
    issueDate: "September 2023",
    expiryDate: "September 2026",
    credentialId: "CEH-2023-TM-334455",
    description:
      "Comprehensive certification covering ethical hacking methodologies, penetration testing, and cybersecurity best practices.",
    skills: [
      "Penetration Testing",
      "Vulnerability Assessment",
      "Network Security",
      "Web Application Security",
    ],
    score: "91%",
    certificateUrl:
      "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
    verifyUrl: "https://aspen.eccouncil.org/verify/334455",
  },
  {
    id: 7,
    title: "TensorFlow Developer Certificate",
    organization: "Google AI",
    category: "ai",
    status: "Active",
    issueDate: "August 2023",
    expiryDate: "August 2026",
    credentialId: "TF-DEV-2023-TM-667788",
    description:
      "Practical certification demonstrating ability to build and deploy machine learning models using TensorFlow.",
    skills: [
      "TensorFlow",
      "Neural Networks",
      "Deep Learning",
      "Computer Vision",
      "NLP",
      "Model Deployment",
    ],
    score: "89%",
    certificateUrl: "https://www.tensorflow.org/certificate",
    verifyUrl: "https://www.credential.net/667788",
  },
  {
    id: 8,
    title: "Azure Fundamentals",
    organization: "Microsoft",
    category: "cloud",
    status: "Active",
    issueDate: "July 2023",
    expiryDate: "Does not expire",
    credentialId: "AZ-900-2023-TM-990011",
    description:
      "Foundational certification covering core Azure services, pricing, and support options.",
    skills: [
      "Azure Services",
      "Virtual Machines",
      "Storage",
      "Networking",
      "Azure AD",
      "Pricing",
    ],
    score: "87%",
    certificateUrl:
      "https://docs.microsoft.com/en-us/learn/certifications/azure-fundamentals/",
    verifyUrl: "https://www.credly.com/badges/990011",
  },
  {
    id: 9,
    title: "Node.js Application Developer",
    organization: "OpenJS Foundation",
    category: "development",
    status: "Active",
    issueDate: "June 2023",
    expiryDate: "June 2026",
    credentialId: "NODEJS-2023-TM-223344",
    description:
      "Professional certification validating skills in building scalable applications with Node.js and related technologies.",
    skills: [
      "Node.js",
      "Express.js",
      "REST APIs",
      "Authentication",
      "Database Integration",
      "Testing",
    ],
    score: "93%",
    certificateUrl: "https://openjsf.org/certification/",
    verifyUrl: "https://training.linuxfoundation.org/verify/223344",
  },
  {
    id: 10,
    title: "Scrum Master Certified (SMC)",
    organization: "Scrum Alliance",
    category: "general",
    status: "Active",
    issueDate: "May 2023",
    expiryDate: "May 2025",
    credentialId: "SMC-2023-TM-556677",
    description:
      "Certification demonstrating understanding of Scrum framework and ability to facilitate agile development processes.",
    skills: [
      "Scrum Framework",
      "Agile Development",
      "Sprint Planning",
      "Team Facilitation",
      "Product Backlog",
    ],
    score: "86%",
    certificateUrl:
      "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster",
    verifyUrl: "https://www.scrumalliance.org/community/profile/556677",
  },
];
