export const certifications = [
  {
    id: 1,
    title: "Oracle Cloud Infrastructure 2025 Certified DevOps Professional",
    organization: "Oracle",
    category: "devops",
    status: "Active",
    issueDate: "October 2025",
    expiryDate: "October 2027",
    credentialId: null,
    description:
      "Professional-level certification validating expertise in DevOps practices on Oracle Cloud Infrastructure, including Kubernetes, Infrastructure as Code, and CI/CD automation.",
    skills: [
      "Kubernetes",
      "Terraform",
      "DevOps",
      "Infrastructure as Code (IaC)",
      "CI/CD",
      "Cloud Architecture",
    ],
    score: null,
    certificateUrl: "#",
    verifyUrl: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=C14FEE9C6EFC4CEE46D0FFDA695C256DE0EFE0579391D36835E92EE682085499",
    logo: "",
  },
  {
    id: 2,
    title: "Multicloud Network Associate",
    organization: "Aviatrix",
    category: "cloud",
    status: "Active",
    issueDate: "September 2025",
    expiryDate: "September 2028",
    credentialId: null,
    description:
      "Certification focused on multicloud networking fundamentals, cloud application connectivity, and AWS-based network architectures.",
    skills: [
      "AWS",
      "Cloud Networking",
      "Multicloud Architecture",
      "Cloud Applications",
    ],
    score: null,
    certificateUrl: "#",
    verifyUrl: "https://www.credly.com/badges/640dba63-8a63-4067-9204-3927cdf2e177/linked_in_profile",
    logo: "",
  },
  {
    id: 3,
    title:
      "Oracle Cloud Infrastructure 2025 Certified Multicloud Architect Professional",
    organization: "Oracle",
    category: "cloud",
    status: "Active",
    issueDate: "September 2025",
    expiryDate: "September 2027",
    credentialId: "cb249959WL53I",
    description:
      "Advanced certification demonstrating expertise in designing and managing multicloud and hybrid cloud architectures across Oracle Cloud, Azure, and Google Cloud.",
    skills: [
      "Multicloud Architecture",
      "Oracle Cloud Infrastructure",
      "Microsoft Azure",
      "Google Cloud Platform (GCP)",
      "Hybrid Cloud",
      "Cloud Computing",
    ],
    score: null,
    certificateUrl: "#",
    verifyUrl: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=7D9860D40DE31AE8986446F9DA817517B578E18802D734B39C5E6D52F2C0B134",
    logo: "",
  },
  {
    id: 4,
    title: "Introduction to IoT",
    organization: "Cisco",
    category: "iot",
    status: "Active",
    issueDate: "June 2024",
    expiryDate: "Does not expire",
    credentialId: null,
    description:
      "Foundational certification covering IoT concepts, embedded systems, backend integration, and cloud-connected device architectures.",
    skills: [
      "Internet of Things (IoT)",
      "Embedded Systems",
      "Backend Development",
      "AWS",
      "Software Development",
    ],
    score: null,
    certificateUrl: "#",
    verifyUrl: "https://www.credly.com/badges/53958f8c-144d-4b24-80a4-b8aa4320d3c4/linked_in_profile",
    logo: "",
  },
];
